### ISSUE TITLE
Why is the version 3.5.0.l? I can't find the corresponding artifact.

### ISSUE THREAD

**Issue by jfclere** [web-servers/noe-core#101]
https://github.com/web-servers/noe-core/blob/a69e8257afe6a0c3214f064f0f955f3bd04b22fe/pom.xml#L102

**Comment by Karm** [comment]
@jfclere It comes from: https://github.com/Karm/okhttp/commit/1082895d16169cb8441cd80f408eb79a757fddfc

**Comment by Karm** [comment]
And it used to be built and deployed in internal Nexus.

**Comment by Karm** [comment]
The purpose was to make ALPN hack Http2 to work. I think that it is long obsolete and could be removed...     @jstefl  and @mmadzin will know.

**Comment by sgala** [comment]
Fixed by #456069 on July 20th. I don't have karma to close the bug.

**Comment by jfclere** [comment]
closed by @sgala
