### ISSUE TITLE
AS7Domain#shiftPorts does not change server-one port for WildFly 13 and newer

### ISSUE THREAD

**Issue by zebrik** [web-servers/noe-core#33]
... the reason is [WFCORE-3771 fix](https://github.com/wildfly/wildfly-core/commit/7413eb78643ac1db4661345d9b1f6080fc6fc80c#diff-1ba6652146b16f999fd5d875d9b09b02) .

**Comment by m-czernek** [comment]
@honza-kasik might find this interesting, as he's also hit by this. Thank you for the report.

**Comment by m-czernek** [comment]
Fix provided. The caveat being that EAP/WF in domain mode is now not working for anything older than EAP 7.2.0 CD14.
